[toolchain]
# Needs to be compiled with the same rust version that the RPC loading this plugin was compiled with.
# https://github.com/anza-xyz/agave/blob/master/rust-toolchain.toml
channel = "1.90.0"
components = ["rustfmt", "rustc-dev", "clippy", "cargo"]
