[package]
name = "jito-protos"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
prost = "0.13"
prost-types = "0.13"
tonic = "0.13.1"

[build-dependencies]
tonic-build = "0.13.1"
